services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
    - 3000:3000
    depends_on:
      - auth-service
  auth-service:
    environment:
      AUTH_DEFAULT_PASSWORD: myverysecretpassword
      AUTH_POSTGRES_HOST: postgres
      AUTH_USE_REAL_DB: 1
    build: ./auth
    container_name: auth-service
    depends_on:
    - postgres
    ports:
    - 8080:8080
  nurse-api:
    environment:
      AUTH_POSTGRES_HOST: postgres
    build: 
      context: ./nurse-api
    container_name: nurse-api
    depends_on:
    - postgres
    ports:
    - 8081:8081
    volumes:
    - ${PWD}/deployments/docker-compose/nurse_api_config:/config/
  phr-manager:
    environment:
      AUTH_HOST: auth-service
      MONGO_HOST: mongo
    build: ./phr-manager
    container_name: phr-manager
    depends_on:
    - mongo
    - auth-service
    ports:
    - 8083:8083  
  statistics:
    environment:
      AUTH_HOST: auth-service
      MONGO_HOST: mongo
    build: ./statistics
    container_name: statistics
    ports:
    - 8084:8084
    depends_on:
      - mongo
      - auth-service
  group-phr-controller:
    environment:
      AUTH_HOST: auth-service
      AUTH_POSTGRES_HOST: postgres
      MONGO_HOST: mongo
    build: 
      context: ./group-phr-controller
    container_name: group-phr-controller
    depends_on:
    - postgres
    - mongo
    - auth-service
    ports:
    - 8085:8085
  disease-service:
    build: ./disease-service
    container_name: disease-service
    ports:
    - 8086:8086
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    image: postgres
    volumes:
      - ${PWD}/deployments/docker-compose/postgres_data:/data
      - ${PWD}/deployments/docker-compose/postgres:/docker-entrypoint-initdb.d/
  mongo:
    container_name: mongo
    environment: 
      MONGO_INITDB_DATABASE: patient_data
    ports:
    - 27017:27017
    image: mongo
    volumes:
      - ${PWD}/deployments/docker-compose/mongo:/docker-entrypoint-initdb.d/