/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.clouditor.examples.patient_community;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    var classUnderTest = new NurseApp();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
