name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-auth-service:
    name: Build Authentication Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v ./...
        working-directory: auth
      - name: Test
        run: go test -v ./...
        working-directory: auth

  build-nurse-api:
    name: Build Nurse API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build
        run: |
          ./gradlew --parallel build
