server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: ES256
          issuer-uri: http://localhost:8080/auth
          jwk-set-uri: http://localhost:8080/auth/credentials
